// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmezGlrxMt2YzAUSpk-MCuFkJ0I8UtH4',
    appId: '1:625775165700:web:7904f6ca7dbe7e875cd051',
    messagingSenderId: '625775165700',
    projectId: 'ecommerc-b08be',
    authDomain: 'ecommerc-b08be.firebaseapp.com',
    databaseURL: 'https://ecommerc-b08be-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerc-b08be.appspot.com',
    measurementId: 'G-W8PR04JPYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0j3E9_KXxSrPknBdBuza_rcDMOqHwkDc',
    appId: '1:625775165700:android:789ea7eaadc6d5f25cd051',
    messagingSenderId: '625775165700',
    projectId: 'ecommerc-b08be',
    databaseURL: 'https://ecommerc-b08be-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerc-b08be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtT1V2rqGitmMsXhsXPXxV2WXpO398ZPo',
    appId: '1:625775165700:ios:fa783239dee4d2395cd051',
    messagingSenderId: '625775165700',
    projectId: 'ecommerc-b08be',
    databaseURL: 'https://ecommerc-b08be-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerc-b08be.appspot.com',
    androidClientId: '625775165700-fnpdprdr3a4j36jme6men1qhn3v0usgm.apps.googleusercontent.com',
    iosClientId: '625775165700-63hm7gkmbfu77ns3jik0goitc5pbq2g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtT1V2rqGitmMsXhsXPXxV2WXpO398ZPo',
    appId: '1:625775165700:ios:fa783239dee4d2395cd051',
    messagingSenderId: '625775165700',
    projectId: 'ecommerc-b08be',
    databaseURL: 'https://ecommerc-b08be-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerc-b08be.appspot.com',
    androidClientId: '625775165700-fnpdprdr3a4j36jme6men1qhn3v0usgm.apps.googleusercontent.com',
    iosClientId: '625775165700-63hm7gkmbfu77ns3jik0goitc5pbq2g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmezGlrxMt2YzAUSpk-MCuFkJ0I8UtH4',
    appId: '1:625775165700:web:8050b6aa3d279b4f5cd051',
    messagingSenderId: '625775165700',
    projectId: 'ecommerc-b08be',
    authDomain: 'ecommerc-b08be.firebaseapp.com',
    databaseURL: 'https://ecommerc-b08be-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerc-b08be.appspot.com',
    measurementId: 'G-XFHNCK9RJ4',
  );
}
